spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.url=jdbc:sqlserver://DESKTOP-B4MHUUV:1433;databaseName=QLRCP;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=00000000
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.web=DEBUG
spring.web.resources.static-locations=classpath:/static/,file:uploads/